services:
  whisper-cpp:
    build:
      context: ./whisper-cpp
      args:
        - WHISPER_CPP_VERSION=1.7.4
        - BUILD_FROM=intel/oneapi:2025.0.1-0-devel-ubuntu24.04
    hostname: whispercpp
    restart: unless-stopped
    depends_on:
      model-download:
        condition: service_completed_successfully
    user: ${PUID}:${PGID}
    group_add:
      - ${RENDER_PGID}
    security_opt:
      - no-new-privileges:true
    environment:
      SYCL_CACHE_PERSISTENT: '1'
      SYCL_CACHE_DIR: /models/sycl_cache
      SYCL_DEVICE_ALLOWLIST: 'BackendName:level_zero'
    volumes:
      - whisper-models:/models
    devices:
      - /dev/dri:/dev/dri
    command: build/bin/whisper-server -l ${WHISPER_LANG} -bs ${WHISPER_BEAM_SIZE} -m /models/ggml-${WHISPER_MODEL}.bin --host 0.0.0.0 --port 8910 --suppress-nst --prompt "${WHISPER_PROMPT}"
  wyoming-api:
    build:
      context: ./wyoming-api
      args:
        - BUILD_FROM=debian:bookworm-slim
    restart: unless-stopped
    depends_on:
      whisper-cpp:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    user: ${PUID}:${PGID}
    ports:
      - 7891:7891
    command: script/run --uri tcp://0.0.0.0:7891 --api http://whispercpp:8910/inference
  model-download:
    build:
      context: ./model-download
    restart: no
    security_opt:
      - no-new-privileges:true
    user: ${PUID}:${PGID}
    environment:
      MODEL: ${WHISPER_MODEL}
    volumes:
      - whisper-models:/models

volumes:
  whisper-models:
    name: whisper-models
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${WHISPER_MODELS_DIR}

networks:
  default:
    name: whisper
